version: '3.3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bUTF06oA753
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=kZgF06oA7zN
    ports:
      - "6379:6379"
